language: python
python:
#  - "3.4"
  - "2.7"
#  - "2.6"

env: 
  - POSTGRESQL_VERSION=9.0
  - POSTGRESQL_VERSION=9.1
  - POSTGRESQL_VERSION=9.2
  - POSTGRESQL_VERSION=9.3
  - POSTGRESQL_VERSION=9.4

install: 
  - "pip install -r requirements.txt"
  - "python setup.py install"

before_script:
  - ".travis/install_postgres.sh"

script:  
  - "export PG_PORT=`pg_lsclusters -h | grep $POSTGRESQL_VERSION | cut -d ' ' -f 3`"
  - "echo $PG_PORT"
  - "cd test && python PgSQLTestCases.py"
  - "cd regression"
  - "python array.py"
  - "python pgconnection.py"
  - "python pgresult.py"
  - "python pgversion.py"
  - "python unicode_tests.py"



